Rewrite `compare_src_locs` implementation to have a total order
immunant/c2rust pull request #1128
Opened 2024-09-18 13:46 UTC by Kriskras99

This implementation is simplified compared to the previous one. It is also almost twice as slow in [the exhaustive test](https://github.com/immunant/c2rust/issues/1126#issuecomment-2354876003) (15 vs 25 seconds).
However, in real sort usage the impact should be significantly less.

Fixes #1126

2024-09-18 23:13 UTC, kkysen reviewed
Thanks!  This looks a lot better, and the better comments help a lot as well.

Is there a test we can add to make sure this is working as intended (correctly sorted, no panics)?

2024-09-19 16:11 UTC, Kriskras99 commented
I've added a test for the total order, based on a reduced test case from the issue (apparently creduce can reduce any text file).
I've also included your code suggestions.

2024-09-19 23:41 UTC, kkysen requested changes

2024-09-19 23:41 UTC, kkysen commented on c2rust-transpile/src/c_ast/mod.rs
> +        locs.sort_unstable_by(|a, b| ctx.compare_src_locs(a, b));
Can you put this below the transitivity checks, as the transitivity checks give better error messages when they fail?

2024-09-19 23:41 UTC, kkysen commented on c2rust-transpile/src/c_ast/mod.rs
> +                    }
We need to use `compare_src_locs` here, not the `impl Ord`.

```suggestion
                    let ab = a.cmp(b);
                    let bc = b.cmp(c);
                    let ac = a.cmp(c);
                    if ab == bc {
                        assert_eq!(ab, ac, "Total order (transivitity) has been violated");
                    }
```

2024-09-20 21:26 UTC, Kriskras99 commented
Not sure what my IDE did to the imports but I'll fix it, I'll also fix your other suggestions. But it will have to wait until after the weekend

2024-09-20 21:30 UTC, kkysen commented
> Not sure what my IDE did to the imports but I'll fix it, I'll also fix your other suggestions. But it will have to wait until after the weekend

No problem, no rush.

2024-09-30 18:46 UTC, Kriskras99 commented
@kkysen I've included your suggestions. Is there anything else that needs to change?

2024-10-03 08:27 UTC, kkysen approved these changes

2024-10-03 08:28 UTC, kkysen commented on c2rust-transpile/src/c_ast/mod.rs
> +                        assert_eq!(ab, ac, "Total order has been violated");
```suggestion
                        assert_eq!(ab, ac, "Total order (transitivity) has been violated");
```

Oh, one last thing, I think it's useful to point out that transitivity is specifically the part of the total order that is violated here.

2024-10-03 08:54 UTC, Kriskras99 commented
Added your last suggestion

2024-10-03 10:03 UTC, kkysen commented
CI seems to be failing, only on Darwin, for some reason:

[CI](https://dev.azure.com/immunant/c2rust/_build/results?buildId=4167&view=logs&jobId=24cae736-ab81-5834-0476-aadc3600cb65&j=24cae736-ab81-5834-0476-aadc3600cb65&t=c6f6f11b-ccbd-5acf-9dd1-ac39967eed7a)

```shell
/Users/runner/work/1/s/tests/statics/src/thread_locals.c:4:17: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
static __thread gsti = 37;
~~~~~~~~~~~~~~~ ^
int
/Users/runner/work/1/s/tests/statics/src/thread_locals.c:5:17: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
extern __thread geti;
~~~~~~~~~~~~~~~ ^
int
/Users/runner/work/1/s/tests/statics/src/thread_locals.c:12:21: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
    static __thread fsti = 59;
    ~~~~~~~~~~~~~~~ ^
    int
/Users/runner/work/1/s/tests/statics/src/thread_locals.c:13:21: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
    extern __thread feti;
    ~~~~~~~~~~~~~~~ ^
    int
```

This doesn't seem to be related to the changes, here, though, so I'm not sure what's happening.

2024-10-03 12:31 UTC, Kriskras99 commented
Maybe the darwin image got updated or something? I really don't see how this change can cause this

2024-10-03 12:33 UTC, Kriskras99 commented
Could you try triggering the CI on the last commit in master? See if it has the same failure

2024-10-23 21:47 UTC, Kriskras99 commented
@kkysen with your CI fix from yesterday, this PR is now green again.

2024-10-24 05:43 UTC, kkysen commented
> @kkysen with your CI fix from yesterday, this PR is now green again.

Awesome!  I'll merge this now.  Sorry for the delay with the CI, and thanks for fixing this!

2024-10-24 05:44 UTC, merged

2024-10-24 06:23 UTC, kkysen commented
Oops, I'm now getting a different CI error in the CI workflow that won't run on outside contributors' PRs correctly: https://github.com/immunant/c2rust/actions/runs/11493361902/job/31988919249.  Do you have an idea of what this might be?  Sorry this CI workflow still isn't set up to correctly run on external PRs.

2024-10-24 08:54 UTC, Kriskras99 commented
Maybe a path confusion? If you look at the first error:
```
error[E0422]: cannot find struct, variant or union type `C2RustUnnamed_4` in this scope
    --> src/lib/conncache.rs:3264:38
     |
3264 |                 __sigaction_handler: C2RustUnnamed_4 {
     |                                      ^^^^^^^^^^^^^^^ not found in this scope
     |
help: consider importing one of these items
     |
3293 |     use crate::src::lib::conncache::C2RustUnnamed_4;
     |
       and 28 other candidates
```
It seems that C2RustUnnamed_4 is put in `src/src/lib/conncache.rs` instead of `src/lib/conncache.rs` and therefore requiring an import. But I haven't looked into c2rust-testsuite enough to understand what it's doing.