feed original MIR location to PDG node
immunant/c2rust pull request #583
Opened 2022-08-05 16:33 UTC by aneksteind

addresses #581

2022-08-09 19:39 UTC, fw-immunant commented on dynamic_instrumentation/src/instrument.rs
> +use crate::point::InstrumentationPointCollectorVisitor;
I hate to nitpick when I'd already commented on this point, but `InstrumentationPointCollectorVisitor` stutters in a way that makes it sound like it's a visitor of `InstrumentationPointCollector`s. I think a verb-like name is ideal, as a visitor class/struct exists for the behavior (verb) in its `Visitor` impl. So I would recommend `CollectInstrumentationPoints` or `CollectInstrumentationPointsVisitor`.

A high-level perspective on this is that the whole visitor is an alternative way to write a `collect_instrumentation_points` function.

2022-08-09 19:39 UTC, fw-immunant commented on dynamic_instrumentation/src/instrument.rs
> +    let mut adder = InstrumentationPointCollectorVisitor::new(tcx, hooks, body);
This variable name should also be updated, perhaps to `visitor`, `collector`, or `collect_points`.

2022-08-09 19:40 UTC, fw-immunant requested changes
Location changes look good, but some additional comments on naming that I'd like addressed.

2022-08-10 02:09 UTC, fw-immunant approved these changes

2022-08-10 06:53 UTC, kkysen requested changes
A few comments:

* If this fixes #581, then it needs to say `fixes #581` or one of the other closing keywords, not `addresses`.  I fixed that here and in another PR.
* The renaming changes should be in a separate PR.  As far as I can tell, they have nothing to do with the functional changes in this PR.
* From what I can tell, `debug_mir` isn't necessary anymore (or it could take no argument) as that information is already there in the `original_location`.
* It'd be helpful if you could give a bit of a description for the PRs.  If the the issue is a description of the bug, then the PR should have a description of how this fixes it, things considered, any other changes, etc.

2022-08-10 17:34 UTC, kkysen commented on dynamic_instrumentation/src/point/build.rs
> +    fn add(&mut self, builder: InstrumentationBuilder<'a, 'tcx>) {
I don't think `add` should take a whole `InstrumentationBuilder`, as that passes extra things that `add` doesn't need, like some fields and a lifetime.  The lifetime isn't an issue now, but I think minimizing lifetimes where possible is generally very useful, and once things get hairy with lifetimes, it gets hard.  Instead, we can just change the `loc: Location` arg to `original_location: Location, instrumentation_location: Location`.

2022-08-10 17:42 UTC, kkysen requested changes
Looks all good now except for the `fn add` comment.

2022-08-10 17:46 UTC, kkysen approved these changes

2022-08-10 18:22 UTC, merged