Update path to homebrew LLVM in README
immunant/c2rust pull request #711
Opened 2022-10-23 16:14 UTC by LegNeato

On my system homebrew installed LLVM into `/opt/homebrew/opt/llvm/bin/llvm-config`. After using this updated path, `c2rust` master built successfully. I believe my homebrew is stock.

2022-10-24 23:03 UTC, kkysen commented
Is this the M1 path?  Maybe we should just list both paths, and in `c2rust-ast-exporter`, too, where it looks in a bunch of paths for `llvm-config`.

2022-10-24 23:26 UTC, kkysen requested changes
`/opt/homebrew` is used by `hombrew` on M1 macs, but `/usr/local/` is still used on Intel macs, and we want to support both.  So we should list both paths in the `README.md`, and potentially also say one is for Intel macs and one is for M1 macs (M2, etc., too).

These paths are also hardcoded in `c2rust-build-paths/src/lib.rs` and `c2rust-analyze/tests/filecheck.rs`.  The latter is meant to be consolidated under `c2rust-build-paths`.  We need to also update these to include the M1 `homebrew` paths.

2022-11-01 05:33 UTC, kkysen approved these changes
We'll probably want to eventually generate all these different but similar paths to search, or search by glob/regex or something, but for now, this looks great and updates things in all the right places I believe.

2022-11-18 16:38 UTC, kkysen commented
By the way, @fw-immunant, I think we should merge this before publishing a new `c2rust` version.

2022-11-18 16:47 UTC, fw-immunant commented
> By the way, @fw-immunant, I think we should merge this before publishing a new `c2rust` version.

I agree. This looks good to me, but I'm not familiar with Homebrew/macOS. Should we wait for @thedataking to review, or just go ahead and merge?

2022-11-18 21:15 UTC, kkysen commented
@thedataking doesn't have an M1, right?  We can wait for him to take a quick look, but I'm not sure he'll have any extra insight.  I think if it works on both on @LegNeato's M1 mac and @thedataking's Intel mac it should be good.

2022-11-24 00:41 UTC, thedataking approved these changes
LGTM. Note that the CI workflow already tests Intel Macs. 

nit: since this patch also fixes capitalization, it should use ARM, not Arm, since it is an acronym. We could also just say Intel Macs and Apple Silicon Macs. No big deal though.

2022-11-28 11:26 UTC, merged