provide stubbed lighttpd connection path
immunant/c2rust pull request #727
Opened 2022-11-15 16:50 UTC by aneksteind

2022-11-15 17:39 UTC, spernsteiner commented
This looks like a reasonable next step for the static analysis.  The one thing I'd suggest changing is removing the `handler` and `ctx` fields, at least for now.  That will let us focus on structs and malloc/free first, and once that's working, we can move on to the function pointer and `void*` cast support that's required for `handler` and `ctx`.

2022-11-15 18:39 UTC, kkysen commented
How do we test static analysis against this?

2022-11-15 18:43 UTC, aneksteind commented
@kkysen currently:
```
$ cd c2rust/analysis
$ cargo run --bin c2rust-analyze -- ../analysis/test/src/lighttpd.rs -L "$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib" --crate-type rlib
```

2022-11-15 23:51 UTC, kkysen requested changes
I think this looks good.  A couple of comments:

* We need to make sure no UB was introduced, like had been in `pointers.rs` when manually adding in code, including from `lighttpd`, especially if that UB is not present in the original C code or transpiled Rust, but is manually introduced by mistake.
* Can we add that command to run static analysis on this as a bash script?
  * This is the only (simple) change for this PR I think we need now.
* I'll file an issue to track splitting this into a working (for static analysis) subset, the original `lighttpd` version, and this version that I'll gradually add more to from the `lighttpd` code.

2022-11-19 00:48 UTC, kkysen approved these changes
I'm going to just merge this as is, and then open other PRs to move things around, add the script, split it into multiple versions, etc.

2022-11-19 00:49 UTC, kkysen commented
> This looks like a reasonable next step for the static analysis. The one thing I'd suggest changing is removing the `handler` and `ctx` fields, at least for now. That will let us focus on structs and malloc/free first, and once that's working, we can move on to the function pointer and `void*` cast support that's required for `handler` and `ctx`.

@spernsteiner, we'll address this in a later PR once we split things up as described in #728.

2022-11-19 01:11 UTC, merged