(`c2rust-analyze/tests`) Switch from simple directives to `clap`-parsed args for analyze tests
immunant/c2rust pull request #869
Opened 2023-03-17 09:32 UTC by kkysen

Switch from simple directives to `clap`-parsed args for analyze tests.

This also adds the `--env` arg, which is needed to set `RUST_LOG_PANIC` in #855 to allow its tests to work.  This is more complex than just implementing logic like setting `RUST_LOG_PANIC` inline in a `#[test] fn` in `c2rust-analyze/tests/filecheck.rs`, but has the benefit of keeping all the testing parameters within the test file itself, as @spernsteiner pointed out.

This switches the previous simple directives (just boolean flags, `,`-separated) to full `clap`- and `shlex`-parsed args because we need arg values and so that we don't waste any time re-implementing parsing.  It's also very easy to just add a `//! --help` to see all the options for args now.

2023-03-17 17:05 UTC, aneksteind commented
why does this have a base associated with #835?

2023-03-17 17:54 UTC, kkysen commented
> why does this have a base associated with #835?

It's meant to build on top of it.

2023-03-17 19:17 UTC, aneksteind commented
> It's meant to build on top of it.

@kkysen does it need to? If not, let's set the base to `master` and adjust accordingly

2023-03-17 20:11 UTC, kkysen commented
Hmm, I guess you're right.  It doesn't necessarily need #835.  That said, it makes rebasing more complex if the PR stack has to keep changing, as now #855 is based on this one, but also has parts based on #835.

2023-03-17 20:50 UTC, spernsteiner approved these changes
Massive overkill, but it'll work.

2023-03-17 22:09 UTC, aneksteind requested changes
please base on `master`. Any merges into master would affect rebasing to some extent, I don't feel like that difficulty makes a valid reason to merge this into a PR that is already under scrutiny and may not get merged.

2023-03-20 20:33 UTC, kkysen commented
Okay, I'll rebase on `master`, as soon as I figure out how to do that (a simple `git rebase master` doesn't work).

2023-03-25 13:41 UTC, aneksteind approved these changes

2023-03-27 10:59 UTC, merged